name: "RepoC Action"
description: "Initial entry point for the chain of actions"
inputs:
  token:
    description: "GitHub Token (not used here)"
    required: false
runs:
  using: "composite"
  steps:
    - name: Dummy Step
      run: echo "Is this the real life?"
