name: Dummy Action
description: Perform a dummy operation
inputs:
  dummy-input:
    description: "A sample input"
    required: false
runs:
  using: "composite"
  steps:
    - id: dummy-step
      run: echo "Dummy action executed with input: ${{ inputs.dummy-input }}" >> $GITHUB_OUTPUT
      shell: bash
outputs:
  dummy-output:
    description: "Output of the dummy action"
    value: "Dummy action output"
